name: Docker
on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: almerico/kinesis-sender
  UPDATEBOT_VERSION: 1.1.53
  JX_RELEASE_VERSION: 1.0.24
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Infrastructure
        run: |
          echo ${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN}}
          echo -e "https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN}}@github.com" >>  ~/.git-credentials
          mkdir  $HOME/tmp
          curl -Ls https://github.com/jenkins-x/jx-release-version/releases/download/v${JX_RELEASE_VERSION}/jx-release-version_${JX_RELEASE_VERSION}_linux_amd64.tar.gz|  tar xvz -C $HOME/tmp;
          curl -Ls -o $HOME/tmp/updatebot.jar   https://repo1.maven.org/maven2/io/jenkins/updatebot/updatebot/${UPDATEBOT_VERSION}/updatebot-${UPDATEBOT_VERSION}.jar
          sudo cp $HOME/tmp/jx-release-version /usr/bin/jx-release-version
          sudo cp $HOME/tmp/updatebot.jar  /usr/bin/updatebot.jar
          echo "java -jar /usr/bin/updatebot.jar \$@" > $HOME/tmp/updatebot
          sudo cp $HOME/tmp/updatebot  /usr/bin/updatebot
          sudo chmod a+x /usr/bin/updatebot
          jx-release-version > VERSION;
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Push image to GitHub Container Registry
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login ${{ secrets.REGISTRY_SERVER }} --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin          
          docker build . -t ${{ secrets.REGISTRY_SERVER }}/$IMAGE_NAME:$(cat VERSION)
          docker tag ${{ secrets.REGISTRY_SERVER }}/$IMAGE_NAME:$(cat VERSION)  ${{ secrets.REGISTRY_SERVER }}/$IMAGE_NAME:latest
          docker images
          docker push ${{ secrets.REGISTRY_SERVER }}/$IMAGE_NAME:$(cat VERSION)
          docker push ${{ secrets.REGISTRY_SERVER }}/$IMAGE_NAME:latest
      - name: start_test
          docker run docker run  \                        
          --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --env AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
          --env NUMBER_SENDER_THREADS=${{ secrets.NUMBER_SENDER_THREADS }} \
          --env NUMBER_SENDER_RECORDS=${{ secrets.NUMBER_SENDER_RECORDS }} \
          --env DELIVERY_STREAM_NAME=${{ secrets.DELIVERY_STREAM_NAME }} \
          --env SENDER_DEBUG_IS_ON=${{ secrets.SENDER_DEBUG_IS_ON }} ${{ secrets.REGISTRY_SERVER }}/$IMAGE_NAME:$(cat VERSION)

      - name : Find diff
        if: contains(github.ref, 'main')
        run: |
         echo "### changes from previous tag:">diff.md
         git log $(git tag --sort version:refname | tail -n 2 | head -n 1)..$(git tag --sort version:refname | tail -n 1) >> diff.md
         cat diff.md
      - name: Create Release
        #if: contains(github.ref, 'release')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body_path: diff.md
          draft: false
          prerelease: false    
      - name: Updatebot
        if: contains(github.ref, 'release')
        run: updatebot push-regex -r "\s+tag:\s(.*)" -v  "$(cat VERSION)" --previous-line "\s+repository:.*/almerico/kinesis-sender" **/values.yaml

  
