name: Docker
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: almerico/kinesis-sender
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Push image to GitHub Container Registry
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login ${{ secrets.REGISTRY_SERVER }} --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin          
          docker build . -t $IMAGE_NAME:$GITHUB_RUN_ID
          docker tag $IMAGE_NAME:$GITHUB_RUN_ID $IMAGE_NAME:latest
          docker images
          docker push $IMAGE_NAME:$GITHUB_RUN_ID
          docker push $IMAGE_NAME:latest
      - name: start_test
        run: |
          docker run docker run  \                        
          --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --env AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} \
          --env NUMBER_SENDER_THREADS=${{ secrets.NUMBER_SENDER_THREADS }} \
          --env NUMBER_SENDER_RECORDS=${{ secrets.NUMBER_SENDER_RECORDS }} \
          --env DELIVERY_STREAM_NAME=${{ secrets.DELIVERY_STREAM_NAME }} \
          --env SENDER_DEBUG_IS_ON=${{ secrets.SENDER_DEBUG_IS_ON }} $IMAGE_NAME:$GITHUB_RUN_ID
      - name : Find diff
        if: contains(github.ref, 'main')
        run: |
         echo "### changes from previous tag:">diff.md
         git log $(git tag --sort version:refname | tail -n 2 | head -n 1)..$(git tag --sort version:refname | tail -n 1) >> diff.md
         cat diff.md
      - name: Create Release
        #if: contains(github.ref, 'release')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body_path: diff.md
          draft: false
          prerelease: false    
      - name: Updatebot
        if: contains(github.ref, 'release')
        run: updatebot push-regex -r "\s+tag:\s(.*)" -v  "$GITHUB_RUN_ID" --previous-line "\s+repository:.*/almerico/kinesis-sender" **/values.yaml
