name: Docker
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: almerico/kinesis-sender
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Push image to GitHub Container Registry
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login ${{ secrets.REGISTRY_SERVER }} --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin          
          docker build . -t $IMAGE_NAME:$GITHUB_RUN_ID
          docker tag $IMAGE_NAME:$GITHUB_RUN_ID $IMAGE_NAME:latest
          docker images
          docker push $IMAGE_NAME:$GITHUB_RUN_ID
          docker push $IMAGE_NAME:latest
      - name: start_test
        run: |
         #cmd="docker run  --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --env AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} --env NUMBER_SENDER_THREADS=${{ secrets.NUMBER_SENDER_THREADS }} --env NUMBER_SENDER_RECORDS=${{ secrets.NUMBER_SENDER_RECORDS }} --env DELIVERY_STREAM_NAME=${{ secrets.DELIVERY_STREAM_NAME }}   --env SENDER_DEBUG_IS_ON=${{ secrets.SENDER_DEBUG_IS_ON }} $IMAGE_NAME:latest"
         echo docker run  --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}  --env AWS_DEFAULT_REGION=us-east-1  --env NUMBER_SENDER_THREADS=2  --env NUMBER_SENDER_RECORDS=500 --env DELIVERY_STREAM_NAME=loadtest  --env SENDER_DEBUG_IS_ON=false  almerico/kinesis-sender
         docker run  --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}  --env AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }} --env NUMBER_SENDER_THREADS=100  --env NUMBER_SENDER_RECORDS=1 --env DELIVERY_STREAM_NAME=loadtest  --env SENDER_DEBUG_IS_ON=false --env NUMBER_SENDER_SENDS=1000 --env MILISECONDS_BETWEEN_SEND=100  $IMAGE_NAME:latest
